# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-05 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dstore', '0002_auto_20200105_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='artistico',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='artista',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
