# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-05 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dstore', '0004_auto_20200105_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='artista',
            field=models.ImageField(null=True, upload_to='foto_artista'),
        ),
    ]
