# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-05 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dstore', '0006_auto_20200105_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='foto_cover')),
                ('artista', models.ManyToManyField(to='dstore.Artista')),
                ('disquera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dstore.Disquera')),
            ],
        ),
    ]
