# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-05 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dstore', '0007_disco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
