# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dstore', '0009_auto_20200106_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['artistico', 'nombre', 'apellido'], 'verbose_name_plural': 'Artistas'},
        ),
        migrations.AlterModelOptions(
            name='disco',
            options={'ordering': ['titulo', 'fecha_publicacion'], 'verbose_name_plural': 'Discos'},
        ),
        migrations.AlterModelOptions(
            name='disquera',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Disqueras'},
        ),
    ]
