# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dstore', '0010_auto_20200106_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disquera',
            options={'ordering': ['nombre', 'pais'], 'verbose_name_plural': 'Disqueras'},
        ),
        migrations.AlterField(
            model_name='artista',
            name='artista',
            field=models.ImageField(blank=True, null=True, upload_to='foto_artista', verbose_name='Foto Artista'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='artistico',
            field=models.CharField(max_length=30, verbose_name='Artista o Grupo'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='foto_cover', verbose_name='Cover Album'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='titulo',
            field=models.CharField(max_length=90, verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='disquera',
            name='domicilio',
            field=models.CharField(blank=True, max_length=90, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='disquera',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Disquera'),
        ),
        migrations.AlterField(
            model_name='disquera',
            name='pais',
            field=models.CharField(max_length=30, verbose_name='pa\xeds'),
        ),
        migrations.AlterField(
            model_name='disquera',
            name='sitioweb',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
