# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dstore', '0011_auto_20200106_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='artista',
            field=models.ManyToManyField(to='dstore.Artista', verbose_name='Artista(s)'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Publicaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='disquera',
            name='pais',
            field=models.CharField(max_length=30, verbose_name='Pa\xeds'),
        ),
    ]
