# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dstore', '0012_auto_20200106_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disquera',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Compa\xf1\xeda'),
        ),
    ]
