# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dstore', '0013_auto_20200106_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='artistico',
            field=models.CharField(max_length=90, verbose_name='Artista o Grupo'),
        ),
    ]
